using GUID = global::System.Guid;
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {






        /// <summary>
        ///  Returns the link quality of the BSS as a value from 0 to 100, or 0 if `bss` is null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "kawaiifi_bss_link_quality", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte kawaiifi_bss_link_quality(Bss* bss);

        /// <summary>
        ///  Returns the GUID of the network interface, or a zeroed GUID if `interface` is null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "kawaiifi_interface_guid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GUID kawaiifi_interface_guid(Interface* @interface);

        /// <summary>
        ///  Returns the human-readable description of the network interface as a C string, or null if `interface` is null.
        ///  The caller must free the returned string with `kawaiifi_string_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "kawaiifi_interface_description", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* kawaiifi_interface_description(Interface* @interface);

        /// <summary>
        ///  Performs a blocking scan and returns the result, or null on error.
        ///  The caller must free the returned scan with `kawaiifi_scan_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "kawaiifi_interface_scan", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Scan* kawaiifi_interface_scan(Interface* @interface);


    }



}
