name: kawaiifi
base: core26
version: "0.1.0"
summary: Wi-Fi scanner and analyzer
description: |
  KawaiiFi is a Wi-Fi scanner and analyzer.

grade: devel
confinement: strict

slots:
  kawaiifi:
    interface: dbus
    bus: session
    name: fi.kawaii.kawaiifi

apps:
  kawaiifi:
    command: usr/bin/kawaiifi
    desktop: usr/share/applications/fi.kawaii.kawaiifi.desktop
    common-id: fi.kawaii.kawaiifi
    extensions: [gnome]
    plugs:
      - network
      - network-manager
      - network-control
      - home

parts:
  kawaiifi:
    plugin: nil
    source: .
    build-packages:
      - cargo
      - rustc
      - build-essential
      - meson
      - ninja-build
      - pkg-config
      - blueprint-compiler
      - libgtk-4-dev
      - libadwaita-1-dev
      - libfontconfig1-dev
      - libdbus-1-dev
    override-build: |
      export CARGO_HOME="$CRAFT_PART_BUILD/cargo-home"

      meson setup build "$CRAFT_PART_SRC" \
        --prefix=/usr \
        --buildtype=release \
        -Dcargo-home="$CARGO_HOME"

      meson compile -C build
      meson install -C build --destdir "$CRAFT_PART_INSTALL"
